[tools]
"github:adwinying/php" = "8.5"
"github:composer/composer" = "latest"
node = "24"
"npm:figlet" = "latest"

[hooks]
postinstall = """
composer_dir=$(mise where github:composer/composer)
if [ -f "$composer_dir/composer.phar" ]; then
  mv "$composer_dir/composer.phar" "$composer_dir/composer"
fi
"""
enter = """
figlet mixtend
echo "$(composer --version)"
echo "node: $(node --version)"
echo "npm: v$(npm --version)"
"""

[settings]
experimental = true
